//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int ArticleId { get; set; }
        public int like { get; set; }
        public int view { get; set; }
        public int UserId { get; set; }
        public int Comment { get; set; }
        public string Content { get; set; }
        public int Favorite { get; set; }
        public string ArticleName { get; set; }
        public System.DateTime ReleaseDateTime { get; set; }
    }
}
